<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="AdminPage.aspx.cs" Inherits="WebApplication1.AdminPage" %>
<asp:Content ID="Content1" ContentPlaceHolderID="Title" runat="server">
     <title>Admin Page</title>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h2 class="submain_title">
        Страница управления данными
    </h2>

    <div class="image">
        <img src="Styles/админ.png" height="300" class="pic" />
    </div>

    <h2 class="submain_title">
        Работа со свободными билетами:
    </h2>

    <div class="row" style="display: flex;justify-content: center;">
        <a class="text" href="FreeTicketWorks.aspx">Добавить/удалить/проверить наличие свободных билетов</a>
    </div>

    <div class="row" style="display: flex;justify-content: center;">
        <h2 class="submain_title">
                Изменить или удалить данные из таблицы:
        </h2>
    </div>

    <div class="row" style="display: flex;justify-content: center;">
        <section class="col-md-11">
            <h3 class="submain_title">Клиенты</h3>
            <asp:GridView ID="GridView1" runat="server" Width="100%" CssClass="table_text" ForeColor="#E5E1DD" GridLines="None" HorizontalAlign="Center" BackColor="#395464" BorderColor="#462E2F" BorderStyle="Solid" BorderWidth="5px" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataSourceID="Client_table" AllowSorting="True" AutoGenerateColumns="False" DataKeyNames="ID_client" AllowPaging="True">
                <AlternatingRowStyle BackColor="#234153" />
                <Columns>
                    <asp:BoundField DataField="ID_client" HeaderText="ID_client" ReadOnly="True" SortExpression="ID_client"></asp:BoundField>
                    <asp:BoundField DataField="Login" HeaderText="Login" SortExpression="Login"></asp:BoundField>
                    <asp:BoundField DataField="Password" HeaderText="Password" SortExpression="Password"></asp:BoundField>
                    <asp:BoundField DataField="Client_name" HeaderText="Client_name" SortExpression="Client_name"></asp:BoundField>
                    <asp:BoundField DataField="Client_surname" HeaderText="Client_surname" SortExpression="Client_surname"></asp:BoundField>
                    <asp:BoundField DataField="Client_Patronymic" HeaderText="Client_Patronymic" SortExpression="Client_Patronymic"></asp:BoundField>
                    <asp:BoundField DataField="Client_birthday" HeaderText="Client_birthday" SortExpression="Client_birthday"></asp:BoundField>
                    <asp:BoundField DataField="Client_phoneNum" HeaderText="Client_phoneNum" SortExpression="Client_phoneNum"></asp:BoundField>
                    <asp:BoundField DataField="Client_e_mail" HeaderText="Client_e_mail" SortExpression="Client_e_mail"></asp:BoundField>
                </Columns>
            </asp:GridView>
            
            <asp:SqlDataSource ID="Client_table" runat="server" ConnectionString="<%$ ConnectionStrings:MuseumDBConnectionString2 %>" DeleteCommand="DELETE FROM [Clients] WHERE [ID_client] = @ID_client" InsertCommand="INSERT INTO [Clients] ([ID_client], [Login], [Password], [Client_name], [Client_surname], [Client_Patronymic], [Client_birthday], [Client_phoneNum], [Client_e_mail]) VALUES (@ID_client, @Login, @Password, @Client_name, @Client_surname, @Client_Patronymic, @Client_birthday, @Client_phoneNum, @Client_e_mail)" SelectCommand="SELECT * FROM [Clients]" UpdateCommand="UPDATE [Clients] SET [Login] = @Login, [Password] = @Password, [Client_name] = @Client_name, [Client_surname] = @Client_surname, [Client_Patronymic] = @Client_Patronymic, [Client_birthday] = @Client_birthday, [Client_phoneNum] = @Client_phoneNum, [Client_e_mail] = @Client_e_mail WHERE [ID_client] = @ID_client">
            <DeleteParameters>
                <asp:Parameter Name="ID_client" Type="Int32"></asp:Parameter>
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="ID_client" Type="Int32"></asp:Parameter>
                <asp:Parameter Name="Login" Type="String"></asp:Parameter>
                <asp:Parameter Name="Password" Type="String"></asp:Parameter>
                <asp:Parameter Name="Client_name" Type="String"></asp:Parameter>
                <asp:Parameter Name="Client_surname" Type="String"></asp:Parameter>
                <asp:Parameter Name="Client_Patronymic" Type="String"></asp:Parameter>
                <asp:Parameter DbType="Date" Name="Client_birthday"></asp:Parameter>
                <asp:Parameter Name="Client_phoneNum" Type="String"></asp:Parameter>
                <asp:Parameter Name="Client_e_mail" Type="String"></asp:Parameter>
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="Login" Type="String"></asp:Parameter>
                <asp:Parameter Name="Password" Type="String"></asp:Parameter>
                <asp:Parameter Name="Client_name" Type="String"></asp:Parameter>
                <asp:Parameter Name="Client_surname" Type="String"></asp:Parameter>
                <asp:Parameter Name="Client_Patronymic" Type="String"></asp:Parameter>
                <asp:Parameter DbType="Date" Name="Client_birthday"></asp:Parameter>
                <asp:Parameter Name="Client_phoneNum" Type="String"></asp:Parameter>
                <asp:Parameter Name="Client_e_mail" Type="String"></asp:Parameter>
                <asp:Parameter Name="ID_client" Type="Int32"></asp:Parameter>
            </UpdateParameters>
        </asp:SqlDataSource>

        </section>
    </div>

    <div class="row" style="display: flex;justify-content: center;">
        <section class="col-md-3">
            <h3 class="submain_title">Тип мероприятия</h3>

            <asp:GridView ID="GridView2" runat="server" Width="100%" CssClass="table_text" ForeColor="#E5E1DD" GridLines="None" HorizontalAlign="Center" BackColor="#395464" BorderColor="#462E2F" BorderStyle="Solid" BorderWidth="5px" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataSourceID="Event_type_table" AllowSorting="True" AutoGenerateColumns="False" DataKeyNames="ID_event_type" AllowPaging="True">
                <AlternatingRowStyle BackColor="#234153" />
                <Columns>
                    <asp:BoundField DataField="ID_event_type" HeaderText="ID_event_type" ReadOnly="True" InsertVisible="False" SortExpression="ID_event_type"></asp:BoundField>
                    <asp:BoundField DataField="Event_type" HeaderText="Event_type" SortExpression="Event_type"></asp:BoundField>
                </Columns>
            </asp:GridView>

            <asp:SqlDataSource ID="Event_type_table" runat="server" ConflictDetection="CompareAllValues" ConnectionString="<%$ ConnectionStrings:MuseumDBConnectionString2 %>" DeleteCommand="DELETE FROM [Event_type] WHERE [ID_event_type] = @original_ID_event_type AND [Event_type] = @original_Event_type" InsertCommand="INSERT INTO [Event_type] ([Event_type]) VALUES (@Event_type)" OldValuesParameterFormatString="original_{0}" SelectCommand="SELECT * FROM [Event_type]" UpdateCommand="UPDATE [Event_type] SET [Event_type] = @Event_type WHERE [ID_event_type] = @original_ID_event_type AND [Event_type] = @original_Event_type">
            <DeleteParameters>
                <asp:Parameter Name="original_ID_event_type" Type="Int32"></asp:Parameter>
                <asp:Parameter Name="original_Event_type" Type="String"></asp:Parameter>
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="Event_type" Type="String"></asp:Parameter>
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="Event_type" Type="String"></asp:Parameter>
                <asp:Parameter Name="original_ID_event_type" Type="Int32"></asp:Parameter>
                <asp:Parameter Name="original_Event_type" Type="String"></asp:Parameter>
            </UpdateParameters>
        </asp:SqlDataSource>

        </section>

        <section class="col-md-1"></section>

        <section class="col-md-6">
            <h3 class="submain_title">Новые мероприятия</h3>

            <asp:GridView ID="GridView3" runat="server" Width="100%" CssClass="table_text" ForeColor="#E5E1DD" GridLines="None" HorizontalAlign="Center" BackColor="#395464" BorderColor="#462E2F" BorderStyle="Solid" BorderWidth="5px" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AllowSorting="True" AutoGenerateColumns="False" AllowPaging="True" DataSourceID="Poster_table" DataKeyNames="ID_event">
                <AlternatingRowStyle BackColor="#234153" />
                <Columns>
                    <asp:BoundField DataField="ID_event" HeaderText="ID_event" ReadOnly="True" InsertVisible="False" SortExpression="ID_event"></asp:BoundField>
                    <asp:BoundField DataField="ID_event_type" HeaderText="ID_event_type" SortExpression="ID_event_type"></asp:BoundField>
                    <asp:BoundField DataField="Event_name" HeaderText="Event_name" SortExpression="Event_name"></asp:BoundField>
                    <asp:BoundField DataField="Event_description" HeaderText="Event_description" SortExpression="Event_description"></asp:BoundField>
                    <asp:BoundField DataField="Ticket_Price" HeaderText="Ticket_Price" SortExpression="Ticket_Price"></asp:BoundField>
                </Columns>
            </asp:GridView>

            <asp:SqlDataSource ID="Poster_table" runat="server" ConflictDetection="CompareAllValues" ConnectionString="<%$ ConnectionStrings:MuseumDBConnectionString2 %>" DeleteCommand="DELETE FROM [Poster] WHERE [ID_event] = @original_ID_event AND [ID_event_type] = @original_ID_event_type AND [Event_name] = @original_Event_name AND [Event_description] = @original_Event_description AND (([Ticket_Price] = @original_Ticket_Price) OR ([Ticket_Price] IS NULL AND @original_Ticket_Price IS NULL))" InsertCommand="INSERT INTO [Poster] ([ID_event_type], [Event_name], [Event_description], [Ticket_Price]) VALUES (@ID_event_type, @Event_name, @Event_description, @Ticket_Price)" OldValuesParameterFormatString="original_{0}" SelectCommand="SELECT * FROM [Poster]" UpdateCommand="UPDATE [Poster] SET [ID_event_type] = @ID_event_type, [Event_name] = @Event_name, [Event_description] = @Event_description, [Ticket_Price] = @Ticket_Price WHERE [ID_event] = @original_ID_event AND [ID_event_type] = @original_ID_event_type AND [Event_name] = @original_Event_name AND [Event_description] = @original_Event_description AND (([Ticket_Price] = @original_Ticket_Price) OR ([Ticket_Price] IS NULL AND @original_Ticket_Price IS NULL))">
                <DeleteParameters>
                    <asp:Parameter Name="original_ID_event" Type="Int32"></asp:Parameter>
                    <asp:Parameter Name="original_ID_event_type" Type="Int32"></asp:Parameter>
                    <asp:Parameter Name="original_Event_name" Type="String"></asp:Parameter>
                    <asp:Parameter Name="original_Event_description" Type="String"></asp:Parameter>
                    <asp:Parameter Name="original_Ticket_Price" Type="Double"></asp:Parameter>
                </DeleteParameters>
                <InsertParameters>
                    <asp:Parameter Name="ID_event_type" Type="Int32"></asp:Parameter>
                    <asp:Parameter Name="Event_name" Type="String"></asp:Parameter>
                    <asp:Parameter Name="Event_description" Type="String"></asp:Parameter>
                    <asp:Parameter Name="Ticket_Price" Type="Double"></asp:Parameter>
                </InsertParameters>
                <UpdateParameters>
                    <asp:Parameter Name="ID_event_type" Type="Int32"></asp:Parameter>
                    <asp:Parameter Name="Event_name" Type="String"></asp:Parameter>
                    <asp:Parameter Name="Event_description" Type="String"></asp:Parameter>
                    <asp:Parameter Name="Ticket_Price" Type="Double"></asp:Parameter>
                    <asp:Parameter Name="original_ID_event" Type="Int32"></asp:Parameter>
                    <asp:Parameter Name="original_ID_event_type" Type="Int32"></asp:Parameter>
                    <asp:Parameter Name="original_Event_name" Type="String"></asp:Parameter>
                    <asp:Parameter Name="original_Event_description" Type="String"></asp:Parameter>
                    <asp:Parameter Name="original_Ticket_Price" Type="Double"></asp:Parameter>
                </UpdateParameters>
            </asp:SqlDataSource>

        </section>
    </div>

    <div class="row" style="display: flex;justify-content: center;">
        <section class="col-md-11">
            <h3 class="submain_title">Экскурсоводы</h3>

            <asp:GridView ID="GridView4" runat="server" Width="100%" CssClass="table_text" ForeColor="#E5E1DD" GridLines="None" HorizontalAlign="Center" BackColor="#395464" BorderColor="#462E2F" BorderStyle="Solid" BorderWidth="5px" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AllowSorting="True" AutoGenerateColumns="False" AllowPaging="True" DataSourceID="Guides_table" DataKeyNames="ID_guide">
                <AlternatingRowStyle BackColor="#234153" />
                <Columns>
                    <asp:BoundField DataField="ID_guide" HeaderText="ID_guide" ReadOnly="True" InsertVisible="False" SortExpression="ID_guide"></asp:BoundField>
                    <asp:BoundField DataField="Guide_name" HeaderText="Guide_name" SortExpression="Guide_name"></asp:BoundField>
                    <asp:BoundField DataField="Guide_surname" HeaderText="Guide_surname" SortExpression="Guide_surname"></asp:BoundField>
                    <asp:BoundField DataField="Guide_patronymic" HeaderText="Guide_patronymic" SortExpression="Guide_patronymic"></asp:BoundField>
                    <asp:BoundField DataField="Guide_experience" HeaderText="Guide_experience" SortExpression="Guide_experience"></asp:BoundField>
                    <asp:BoundField DataField="Guide_phoneNum" HeaderText="Guide_phoneNum" SortExpression="Guide_phoneNum"></asp:BoundField>
                    <asp:BoundField DataField="Guide_e_mail" HeaderText="Guide_e_mail" SortExpression="Guide_e_mail"></asp:BoundField>
                </Columns>
            </asp:GridView>

            <asp:SqlDataSource ID="Guides_table" runat="server" ConflictDetection="CompareAllValues" ConnectionString="<%$ ConnectionStrings:MuseumDBConnectionString2 %>" DeleteCommand="DELETE FROM [Guides] WHERE [ID_guide] = @original_ID_guide AND [Guide_name] = @original_Guide_name AND [Guide_surname] = @original_Guide_surname AND (([Guide_patronymic] = @original_Guide_patronymic) OR ([Guide_patronymic] IS NULL AND @original_Guide_patronymic IS NULL)) AND (([Guide_experience] = @original_Guide_experience) OR ([Guide_experience] IS NULL AND @original_Guide_experience IS NULL)) AND [Guide_phoneNum] = @original_Guide_phoneNum AND [Guide_e_mail] = @original_Guide_e_mail" InsertCommand="INSERT INTO [Guides] ([Guide_name], [Guide_surname], [Guide_patronymic], [Guide_experience], [Guide_phoneNum], [Guide_e_mail]) VALUES (@Guide_name, @Guide_surname, @Guide_patronymic, @Guide_experience, @Guide_phoneNum, @Guide_e_mail)" OldValuesParameterFormatString="original_{0}" SelectCommand="SELECT * FROM [Guides]" UpdateCommand="UPDATE [Guides] SET [Guide_name] = @Guide_name, [Guide_surname] = @Guide_surname, [Guide_patronymic] = @Guide_patronymic, [Guide_experience] = @Guide_experience, [Guide_phoneNum] = @Guide_phoneNum, [Guide_e_mail] = @Guide_e_mail WHERE [ID_guide] = @original_ID_guide AND [Guide_name] = @original_Guide_name AND [Guide_surname] = @original_Guide_surname AND (([Guide_patronymic] = @original_Guide_patronymic) OR ([Guide_patronymic] IS NULL AND @original_Guide_patronymic IS NULL)) AND (([Guide_experience] = @original_Guide_experience) OR ([Guide_experience] IS NULL AND @original_Guide_experience IS NULL)) AND [Guide_phoneNum] = @original_Guide_phoneNum AND [Guide_e_mail] = @original_Guide_e_mail">
            <DeleteParameters>
                <asp:Parameter Name="original_ID_guide" Type="Int32"></asp:Parameter>
                <asp:Parameter Name="original_Guide_name" Type="String"></asp:Parameter>
                <asp:Parameter Name="original_Guide_surname" Type="String"></asp:Parameter>
                <asp:Parameter Name="original_Guide_patronymic" Type="String"></asp:Parameter>
                <asp:Parameter Name="original_Guide_experience" Type="Int32"></asp:Parameter>
                <asp:Parameter Name="original_Guide_phoneNum" Type="String"></asp:Parameter>
                <asp:Parameter Name="original_Guide_e_mail" Type="String"></asp:Parameter>
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="Guide_name" Type="String"></asp:Parameter>
                <asp:Parameter Name="Guide_surname" Type="String"></asp:Parameter>
                <asp:Parameter Name="Guide_patronymic" Type="String"></asp:Parameter>
                <asp:Parameter Name="Guide_experience" Type="Int32"></asp:Parameter>
                <asp:Parameter Name="Guide_phoneNum" Type="String"></asp:Parameter>
                <asp:Parameter Name="Guide_e_mail" Type="String"></asp:Parameter>
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="Guide_name" Type="String"></asp:Parameter>
                <asp:Parameter Name="Guide_surname" Type="String"></asp:Parameter>
                <asp:Parameter Name="Guide_patronymic" Type="String"></asp:Parameter>
                <asp:Parameter Name="Guide_experience" Type="Int32"></asp:Parameter>
                <asp:Parameter Name="Guide_phoneNum" Type="String"></asp:Parameter>
                <asp:Parameter Name="Guide_e_mail" Type="String"></asp:Parameter>
                <asp:Parameter Name="original_ID_guide" Type="Int32"></asp:Parameter>
                <asp:Parameter Name="original_Guide_name" Type="String"></asp:Parameter>
                <asp:Parameter Name="original_Guide_surname" Type="String"></asp:Parameter>
                <asp:Parameter Name="original_Guide_patronymic" Type="String"></asp:Parameter>
                <asp:Parameter Name="original_Guide_experience" Type="Int32"></asp:Parameter>
                <asp:Parameter Name="original_Guide_phoneNum" Type="String"></asp:Parameter>
                <asp:Parameter Name="original_Guide_e_mail" Type="String"></asp:Parameter>
            </UpdateParameters>
        </asp:SqlDataSource>

        </section>
    </div>
    
    <div class="row" style="display: flex;justify-content: center;">
        <section class="col-md-3">

            <h3 class="submain_title">Тип билетов</h3>

            <asp:GridView ID="GridView5" runat="server" Width="100%" CssClass="table_text" ForeColor="#E5E1DD" GridLines="None" HorizontalAlign="Center" BackColor="#395464" BorderColor="#462E2F" BorderStyle="Solid" BorderWidth="5px" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AllowSorting="True" AutoGenerateColumns="False" AllowPaging="True" DataSourceID="Ticket_type_table" DataKeyNames="ID_ticket_type">
                <AlternatingRowStyle BackColor="#234153" />
                <Columns>
                    <asp:BoundField DataField="ID_ticket_type" HeaderText="ID_ticket_type" ReadOnly="True" SortExpression="ID_ticket_type"></asp:BoundField>
                    <asp:BoundField DataField="Ticket_type" HeaderText="Ticket_type" SortExpression="Ticket_type"></asp:BoundField>
                    <asp:BoundField DataField="Ticket_coeff" HeaderText="Ticket_coeff" SortExpression="Ticket_coeff"></asp:BoundField>
                </Columns>
            </asp:GridView>

            <asp:SqlDataSource ID="Ticket_type_table" runat="server" ConflictDetection="CompareAllValues" ConnectionString="<%$ ConnectionStrings:MuseumDBConnectionString2 %>" DeleteCommand="DELETE FROM [Ticket_type] WHERE [ID_ticket_type] = @original_ID_ticket_type AND [Ticket_type] = @original_Ticket_type AND (([Ticket_coeff] = @original_Ticket_coeff) OR ([Ticket_coeff] IS NULL AND @original_Ticket_coeff IS NULL))" InsertCommand="INSERT INTO [Ticket_type] ([ID_ticket_type], [Ticket_type], [Ticket_coeff]) VALUES (@ID_ticket_type, @Ticket_type, @Ticket_coeff)" OldValuesParameterFormatString="original_{0}" SelectCommand="SELECT * FROM [Ticket_type]" UpdateCommand="UPDATE [Ticket_type] SET [Ticket_type] = @Ticket_type, [Ticket_coeff] = @Ticket_coeff WHERE [ID_ticket_type] = @original_ID_ticket_type AND [Ticket_type] = @original_Ticket_type AND (([Ticket_coeff] = @original_Ticket_coeff) OR ([Ticket_coeff] IS NULL AND @original_Ticket_coeff IS NULL))">
             <DeleteParameters>
                 <asp:Parameter Name="original_ID_ticket_type" Type="Int32"></asp:Parameter>
                 <asp:Parameter Name="original_Ticket_type" Type="String"></asp:Parameter>
                 <asp:Parameter Name="original_Ticket_coeff" Type="Double"></asp:Parameter>
             </DeleteParameters>
             <InsertParameters>
                 <asp:Parameter Name="ID_ticket_type" Type="Int32"></asp:Parameter>
                 <asp:Parameter Name="Ticket_type" Type="String"></asp:Parameter>
                 <asp:Parameter Name="Ticket_coeff" Type="Double"></asp:Parameter>
             </InsertParameters>
             <UpdateParameters>
                 <asp:Parameter Name="Ticket_type" Type="String"></asp:Parameter>
                 <asp:Parameter Name="Ticket_coeff" Type="Double"></asp:Parameter>
                 <asp:Parameter Name="original_ID_ticket_type" Type="Int32"></asp:Parameter>
                 <asp:Parameter Name="original_Ticket_type" Type="String"></asp:Parameter>
                 <asp:Parameter Name="original_Ticket_coeff" Type="Double"></asp:Parameter>
             </UpdateParameters>
         </asp:SqlDataSource>

        </section>

        <section class="col-md-1"></section>

        <section class="col-md-6">

            <h3 class="submain_title">События</h3>

            <asp:GridView ID="GridView6" runat="server" Width="100%" CssClass="table_text" ForeColor="#E5E1DD" GridLines="None" HorizontalAlign="Center" BackColor="#395464" BorderColor="#462E2F" BorderStyle="Solid" BorderWidth="5px" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AllowSorting="True" AutoGenerateColumns="False" AllowPaging="True" DataSourceID="Passage_table" DataKeyNames="ID_passage">
                <AlternatingRowStyle BackColor="#234153" />
                <Columns>
                    <asp:BoundField DataField="ID_passage" HeaderText="ID_passage" ReadOnly="True" SortExpression="ID_passage"></asp:BoundField>
                    <asp:BoundField DataField="ID_event" HeaderText="ID_event" SortExpression="ID_event"></asp:BoundField>
                    <asp:BoundField DataField="ID_guide" HeaderText="ID_guide" SortExpression="ID_guide"></asp:BoundField>
                    <asp:BoundField DataField="Event_date" HeaderText="Event_date" SortExpression="Event_date"></asp:BoundField>
                    <asp:BoundField DataField="Event_time" HeaderText="Event_time" SortExpression="Event_time"></asp:BoundField>
                </Columns>
            </asp:GridView>

            <asp:SqlDataSource ID="Passage_table" runat="server" ConflictDetection="CompareAllValues" ConnectionString="<%$ ConnectionStrings:MuseumDBConnectionString2 %>" DeleteCommand="DELETE FROM [Passage] WHERE [ID_passage] = @original_ID_passage AND (([ID_event] = @original_ID_event) OR ([ID_event] IS NULL AND @original_ID_event IS NULL)) AND (([ID_guide] = @original_ID_guide) OR ([ID_guide] IS NULL AND @original_ID_guide IS NULL)) AND [Event_date] = @original_Event_date AND [Event_time] = @original_Event_time" InsertCommand="INSERT INTO [Passage] ([ID_passage], [ID_event], [ID_guide], [Event_date], [Event_time]) VALUES (@ID_passage, @ID_event, @ID_guide, @Event_date, @Event_time)" OldValuesParameterFormatString="original_{0}" SelectCommand="SELECT * FROM [Passage]" UpdateCommand="UPDATE [Passage] SET [ID_event] = @ID_event, [ID_guide] = @ID_guide, [Event_date] = @Event_date, [Event_time] = @Event_time WHERE [ID_passage] = @original_ID_passage AND (([ID_event] = @original_ID_event) OR ([ID_event] IS NULL AND @original_ID_event IS NULL)) AND (([ID_guide] = @original_ID_guide) OR ([ID_guide] IS NULL AND @original_ID_guide IS NULL)) AND [Event_date] = @original_Event_date AND [Event_time] = @original_Event_time">
            <DeleteParameters>
                <asp:Parameter Name="original_ID_passage" Type="Int32"></asp:Parameter>
                <asp:Parameter Name="original_ID_event" Type="Int32"></asp:Parameter>
                <asp:Parameter Name="original_ID_guide" Type="Int32"></asp:Parameter>
                <asp:Parameter DbType="Date" Name="original_Event_date"></asp:Parameter>
                <asp:Parameter DbType="Time" Name="original_Event_time"></asp:Parameter>
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="ID_passage" Type="Int32"></asp:Parameter>
                <asp:Parameter Name="ID_event" Type="Int32"></asp:Parameter>
                <asp:Parameter Name="ID_guide" Type="Int32"></asp:Parameter>
                <asp:Parameter DbType="Date" Name="Event_date"></asp:Parameter>
                <asp:Parameter DbType="Time" Name="Event_time"></asp:Parameter>
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="ID_event" Type="Int32"></asp:Parameter>
                <asp:Parameter Name="ID_guide" Type="Int32"></asp:Parameter>
                <asp:Parameter DbType="Date" Name="Event_date"></asp:Parameter>
                <asp:Parameter DbType="Time" Name="Event_time"></asp:Parameter>
                <asp:Parameter Name="original_ID_passage" Type="Int32"></asp:Parameter>
                <asp:Parameter Name="original_ID_event" Type="Int32"></asp:Parameter>
                <asp:Parameter Name="original_ID_guide" Type="Int32"></asp:Parameter>
                <asp:Parameter DbType="Date" Name="original_Event_date"></asp:Parameter>
                <asp:Parameter DbType="Time" Name="original_Event_time"></asp:Parameter>
            </UpdateParameters>
        </asp:SqlDataSource>

        </section>
    </div>

    <div class="row" style="display: flex;justify-content: center;">
        <section class="col-md-5">
            <h3 class="submain_title">Таблица свободных билетов</h3>
            <asp:GridView ID="GridView7" runat="server" Width="100%" CssClass="table_text" ForeColor="#E5E1DD" GridLines="None" HorizontalAlign="Center" BackColor="#395464" BorderColor="#462E2F" BorderStyle="Solid" BorderWidth="5px" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AllowSorting="True" AutoGenerateColumns="False" AllowPaging="True" DataSourceID="Tickets_table" DataKeyNames="ID_ticket">
                <AlternatingRowStyle BackColor="#234153" />
                <Columns>
                    <asp:BoundField DataField="ID_ticket" HeaderText="ID_ticket" ReadOnly="True" SortExpression="ID_ticket"></asp:BoundField>
                    <asp:BoundField DataField="ID_passage" HeaderText="ID_passage" SortExpression="ID_passage"></asp:BoundField>
                    <asp:BoundField DataField="ID_ticket_type" HeaderText="ID_ticket_type" SortExpression="ID_ticket_type"></asp:BoundField>
                    <asp:BoundField DataField="ID_client" HeaderText="ID_client" SortExpression="ID_client"></asp:BoundField>
                    <asp:BoundField DataField="Reg_data" HeaderText="Reg_data" SortExpression="Reg_data"></asp:BoundField>
                    <asp:BoundField DataField="Summ_price" HeaderText="Summ_price" SortExpression="Summ_price"></asp:BoundField>
                </Columns>
            </asp:GridView>

            <asp:SqlDataSource ID="Tickets_table" runat="server" ConflictDetection="CompareAllValues" ConnectionString="<%$ ConnectionStrings:MuseumDBConnectionString2 %>" DeleteCommand="DELETE FROM [Tickets] WHERE [ID_ticket] = @original_ID_ticket AND [ID_passage] = @original_ID_passage AND [ID_ticket_type] = @original_ID_ticket_type AND (([ID_client] = @original_ID_client) OR ([ID_client] IS NULL AND @original_ID_client IS NULL)) AND (([Reg_data] = @original_Reg_data) OR ([Reg_data] IS NULL AND @original_Reg_data IS NULL)) AND (([Summ_price] = @original_Summ_price) OR ([Summ_price] IS NULL AND @original_Summ_price IS NULL))" InsertCommand="INSERT INTO [Tickets] ([ID_ticket], [ID_passage], [ID_ticket_type], [ID_client], [Reg_data], [Summ_price]) VALUES (@ID_ticket, @ID_passage, @ID_ticket_type, @ID_client, @Reg_data, @Summ_price)" OldValuesParameterFormatString="original_{0}" SelectCommand="SELECT * FROM [Tickets]" UpdateCommand="UPDATE [Tickets] SET [ID_passage] = @ID_passage, [ID_ticket_type] = @ID_ticket_type, [ID_client] = @ID_client, [Reg_data] = @Reg_data, [Summ_price] = @Summ_price WHERE [ID_ticket] = @original_ID_ticket AND [ID_passage] = @original_ID_passage AND [ID_ticket_type] = @original_ID_ticket_type AND (([ID_client] = @original_ID_client) OR ([ID_client] IS NULL AND @original_ID_client IS NULL)) AND (([Reg_data] = @original_Reg_data) OR ([Reg_data] IS NULL AND @original_Reg_data IS NULL)) AND (([Summ_price] = @original_Summ_price) OR ([Summ_price] IS NULL AND @original_Summ_price IS NULL))">
                <DeleteParameters>
                    <asp:Parameter Name="original_ID_ticket" Type="Int32"></asp:Parameter>
                    <asp:Parameter Name="original_ID_passage" Type="Int32"></asp:Parameter>
                    <asp:Parameter Name="original_ID_ticket_type" Type="Int32"></asp:Parameter>
                    <asp:Parameter Name="original_ID_client" Type="Int32"></asp:Parameter>
                    <asp:Parameter DbType="Date" Name="original_Reg_data"></asp:Parameter>
                    <asp:Parameter Name="original_Summ_price" Type="Int32"></asp:Parameter>
                </DeleteParameters>
                <InsertParameters>
                    <asp:Parameter Name="ID_ticket" Type="Int32"></asp:Parameter>
                    <asp:Parameter Name="ID_passage" Type="Int32"></asp:Parameter>
                    <asp:Parameter Name="ID_ticket_type" Type="Int32"></asp:Parameter>
                    <asp:Parameter Name="ID_client" Type="Int32"></asp:Parameter>
                    <asp:Parameter DbType="Date" Name="Reg_data"></asp:Parameter>
                    <asp:Parameter Name="Summ_price" Type="Int32"></asp:Parameter>
                </InsertParameters>
                <UpdateParameters>
                    <asp:Parameter Name="ID_passage" Type="Int32"></asp:Parameter>
                    <asp:Parameter Name="ID_ticket_type" Type="Int32"></asp:Parameter>
                    <asp:Parameter Name="ID_client" Type="Int32"></asp:Parameter>
                    <asp:Parameter DbType="Date" Name="Reg_data"></asp:Parameter>
                    <asp:Parameter Name="Summ_price" Type="Int32"></asp:Parameter>
                    <asp:Parameter Name="original_ID_ticket" Type="Int32"></asp:Parameter>
                    <asp:Parameter Name="original_ID_passage" Type="Int32"></asp:Parameter>
                    <asp:Parameter Name="original_ID_ticket_type" Type="Int32"></asp:Parameter>
                    <asp:Parameter Name="original_ID_client" Type="Int32"></asp:Parameter>
                    <asp:Parameter DbType="Date" Name="original_Reg_data"></asp:Parameter>
                    <asp:Parameter Name="original_Summ_price" Type="Int32"></asp:Parameter>
                </UpdateParameters>
            </asp:SqlDataSource>
        </section>
    </div>

</asp:Content>
